[package]
name = "scheme-to-rust"
version = "0.1.0"
authors = ["Chriscbr <crybicki98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lexpr = "0.2.3"
im-rc = "13.0.0"
